<a href="https://colab.research.google.com/github/000626574705/python/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))     #generate random 3*4 array of element btw 1 to 10

In [3]:
arr

array([[4, 4, 4, 6],
       [9, 7, 8, 4],
       [1, 4, 4, 3]])

In [4]:
arr.reshape(6,2)

array([[4, 4],
       [4, 6],
       [9, 7],
       [8, 4],
       [1, 4],
       [4, 3]])

In [5]:
arr.reshape(2,6)    #reshape the matrix

array([[4, 4, 4, 6, 9, 7],
       [8, 4, 1, 4, 4, 3]])

In [6]:
arr.T     #transpose the matrix

array([[4, 9, 1],
       [4, 7, 4],
       [4, 8, 4],
       [6, 4, 3]])

In [7]:
arr.flatten()      #convert 2d to 1d array

array([4, 4, 4, 6, 9, 7, 8, 4, 1, 4, 4, 3])

In [8]:
arr1 = np.array([1,2,5,4] )

In [10]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1)     #change dimaension fromm one to 2 in axis =1 means row wise

array([[1],
       [2],
       [5],
       [4]])

In [14]:
np.squeeze(arr)

array([[4, 4, 4, 6],
       [9, 7, 8, 4],
       [1, 4, 4, 3]])

In [15]:
data= np.array([[1],[2],[3]])

In [16]:
data

array([[1],
       [2],
       [3]])

In [17]:
np.squeeze(data)

array([1, 2, 3])

In [18]:
arr1

array([1, 2, 5, 4])

In [22]:
np.repeat(arr1,3)     #repeat elements by 3

array([1, 1, 1, 2, 2, 2, 5, 5, 5, 4, 4, 4])

In [21]:
np.roll(arr1,2)     #shift array elements by 2

array([5, 4, 1, 2])

In [24]:
np.diag(arr1)     #put all provided elements  diagonally

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 4]])

In [25]:
#Numpy -Binary operators

In [26]:
arr1 = np.random.randint(1,10,(3,4))

In [38]:
arr2 = np.random.randint(1,10,(3,4))

In [28]:
arr1

array([[2, 6, 7, 3],
       [6, 5, 1, 6],
       [8, 7, 3, 5]])

In [32]:
arr2

array([[3, 1, 9],
       [6, 3, 7],
       [5, 2, 9],
       [5, 9, 3]])

In [34]:
arr2@arr1     #multiplication of two array

array([[ 84,  86,  49,  60],
       [ 86, 100,  66,  71],
       [ 94, 103,  64,  72],
       [ 88,  96,  53,  84]])

In [39]:
arr2+arr1    #addition of two arrays

array([[ 6, 10, 11,  7],
       [12, 11,  4,  9],
       [17, 16, 10, 14]])

In [41]:
arr1-arr2   #subtraction of two arrays

array([[-2,  2,  3, -1],
       [ 0, -1, -2,  3],
       [-1, -2, -4, -4]])

In [42]:
arr1%arr2

array([[2, 2, 3, 3],
       [0, 5, 1, 0],
       [8, 7, 3, 5]])

In [44]:
arr1**arr2      #power of index elements of other ar2

array([[       16,      1296,      2401,        81],
       [    46656,     15625,         1,       216],
       [134217728,  40353607,      2187,   1953125]])

In [45]:
arr1 &arr2

array([[0, 4, 4, 0],
       [6, 4, 1, 2],
       [8, 1, 3, 1]])

In [46]:
arr1 | arr2

array([[ 6,  6,  7,  7],
       [ 6,  7,  3,  7],
       [ 9, 15,  7, 13]])

In [47]:
-arr1

array([[-2, -6, -7, -3],
       [-6, -5, -1, -6],
       [-8, -7, -3, -5]])

In [48]:
arr1>arr2

array([[False,  True,  True, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [49]:
#Numpy string function

In [52]:
stri=np.array(['sudh','kumar'])

In [53]:
np.char.upper(stri)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [54]:
np.char.title(stri)

array(['Sudh', 'Kumar'], dtype='<U5')

In [55]:
np.char.capitalize(stri)

array(['Sudh', 'Kumar'], dtype='<U5')

In [56]:
#Numpy - mathematical Function

In [57]:
arr1

array([[2, 6, 7, 3],
       [6, 5, 1, 6],
       [8, 7, 3, 5]])

In [58]:
np.sin(arr1)

array([[ 0.90929743, -0.2794155 ,  0.6569866 ,  0.14112001],
       [-0.2794155 , -0.95892427,  0.84147098, -0.2794155 ],
       [ 0.98935825,  0.6569866 ,  0.14112001, -0.95892427]])

In [59]:
np.cos(arr1)

array([[-0.41614684,  0.96017029,  0.75390225, -0.9899925 ],
       [ 0.96017029,  0.28366219,  0.54030231,  0.96017029],
       [-0.14550003,  0.75390225, -0.9899925 ,  0.28366219]])

In [60]:
np.log10(arr1)

array([[0.30103   , 0.77815125, 0.84509804, 0.47712125],
       [0.77815125, 0.69897   , 0.        , 0.77815125],
       [0.90308999, 0.84509804, 0.47712125, 0.69897   ]])

In [61]:
np.exp(arr1)

array([[7.38905610e+00, 4.03428793e+02, 1.09663316e+03, 2.00855369e+01],
       [4.03428793e+02, 1.48413159e+02, 2.71828183e+00, 4.03428793e+02],
       [2.98095799e+03, 1.09663316e+03, 2.00855369e+01, 1.48413159e+02]])

In [63]:
np.power(arr1,2)     #to calculate the power of  arr1 to 2

array([[ 4, 36, 49,  9],
       [36, 25,  1, 36],
       [64, 49,  9, 25]])

In [64]:
np.sqrt(arr1)     #to square root   of all elements

array([[1.41421356, 2.44948974, 2.64575131, 1.73205081],
       [2.44948974, 2.23606798, 1.        , 2.44948974],
       [2.82842712, 2.64575131, 1.73205081, 2.23606798]])

In [65]:
np.mean(arr1)

4.916666666666667

In [66]:
np.median(arr1)

5.5

In [67]:
np.var(arr1)

4.409722222222222

In [68]:
np.min(arr1)

1

In [69]:
np.max(arr1)

8