<a href="https://colab.research.google.com/github/000626574705/python/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
l=[1,2,3,4]

In [6]:
ar=np.array(l)    #to convert  list to array

In [7]:
ar

array([1, 2, 3, 4])

In [8]:
type(ar)

numpy.ndarray

In [9]:
np.array([[1,2],[3,4]])    #to convert  list to 2-Darray

array([[1, 2],
       [3, 4]])

In [10]:
np.asarray(l)

array([1, 2, 3, 4])

In [11]:
b=np.matrix([[1,2],[2,8]])

In [12]:
b

matrix([[1, 2],
        [2, 8]])

In [13]:
np.asanyarray(b)

matrix([[1, 2],
        [2, 8]])

In [14]:
c=l     #solo copy

In [15]:
c

[1, 2, 3, 4]

In [16]:
d =np.copy(c)  #deep copy of elements

In [17]:
y=np.array(c)

In [18]:
y

array([1, 2, 3, 4])

In [19]:
z=y      #same space me data available rahega or jo bhi changes honge ek hi space me honge

In [20]:
z[0]

1

In [21]:
z[1]

2

In [22]:
c[1]=100

In [23]:
c

[1, 100, 3, 4]

In [24]:
d =np.copy(z)

In [25]:
d[0]

1

In [26]:
d[0]=450

In [27]:
z

array([1, 2, 3, 4])

In [28]:
np.fromfunction(lambda i,j:i==j ,(3,3) )     #to function are passed generate data on the basis of given function of given dimention


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j:i*j ,(3,3) )

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
iterable = (i*i for i in range(5))     #to generate iterate function from this

In [31]:
np.fromiter(iterable,int)     #to iterate the iterable funvtion and also in the dtypes of integer

array([ 0,  1,  4,  9, 16])

In [32]:
np.fromstring('234 214',sep=' ')

array([234., 214.])

In [33]:
np.fromstring('4,5',sep = ',')

array([4., 5.])

In [34]:
#Numpy -Data Types

In [35]:
l = [2,3,4,5,6]

In [36]:
ar = np.array(l)

In [37]:
ar

array([2, 3, 4, 5, 6])

In [38]:
ar.ndim

1

In [39]:
ar2=np.array([[l],[l]])

In [40]:
ar2

array([[[2, 3, 4, 5, 6]],

       [[2, 3, 4, 5, 6]]])

In [41]:
ar.size

5

In [42]:
ar2.size

10

In [43]:
ar.shape

(5,)

In [44]:
ar2.ndim

3

In [45]:
ar2.dtype

dtype('int64')

In [46]:
ar22 = np.array([(1,4,1,5),(45,5,6,5.2)])

In [47]:
ar22

array([[ 1. ,  4. ,  1. ,  5. ],
       [45. ,  5. ,  6. ,  5.2]])

In [48]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [49]:

list(np.arange(2.3,5.6,.3))      #this will create array from 2.3 to 5.6 and jump of .3

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [50]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros((3,4,2))      # generate 3d array of 4*2 [3times] having zeroes

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [53]:
arr5=np.ones((4,2))          #generate 2d array of 4*2 having one

In [54]:
arr5+6        #add 6 to all elements in the arr5

array([[7., 7.],
       [7., 7.],
       [7., 7.],
       [7., 7.]])

In [55]:
arr5*6

array([[6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.]])

In [56]:
np.empty((3,4))

array([[1.65111363e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [57]:
np.eye(4)     #determinent 1 hota diagonal elements 1 hote h  genrate f 4*4 size

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.linspace(2,5,20)    #take value between 2-4 and present 20 datas

array([2.        , 2.15789474, 2.31578947, 2.47368421, 2.63157895,
       2.78947368, 2.94736842, 3.10526316, 3.26315789, 3.42105263,
       3.57894737, 3.73684211, 3.89473684, 4.05263158, 4.21052632,
       4.36842105, 4.52631579, 4.68421053, 4.84210526, 5.        ])

In [59]:
np.logspace(1,2,5,base=2)    #take value from 1 to 2 produce 10 data

array([2.        , 2.37841423, 2.82842712, 3.36358566, 4.        ])

In [60]:
arr=np.random.randn(3,4)

In [61]:
import pandas as pd

In [62]:
pd.DataFrame(arr)

0         1         2         3
0  1.090239  0.993161 -0.744753 -0.057194
1  1.411349 -0.390843  0.320340  0.938572
2  1.395596 -0.839304  0.057763  0.284009

In [63]:
np.random.rand(3,4)     #generate random value in 3*4 matrix

array([[0.2546954 , 0.63931373, 0.91373583, 0.7632002 ],
       [0.62789046, 0.68105861, 0.52565648, 0.80244967],
       [0.41948848, 0.56184763, 0.14708098, 0.51819645]])

In [64]:
np.random.randint(1,110,(3,4))    #generate random integer from 1 to 110 in the form of 3*4 matrix

array([[68, 23, 92, 54],
       [19, 56, 41, 70],
       [70, 38, 13, 88]])

In [65]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('testdata1.csv')

In [66]:
a=np.random.rand(3,4)

In [67]:
a


array([[0.41007015, 0.6019086 , 0.94094778, 0.83970192],
       [0.75891741, 0.94770639, 0.1271737 , 0.44516779],
       [0.72479702, 0.22678686, 0.73886324, 0.4948045 ]])

In [68]:
a.reshape(6,-2)

array([[0.41007015, 0.6019086 ],
       [0.94094778, 0.83970192],
       [0.75891741, 0.94770639],
       [0.1271737 , 0.44516779],
       [0.72479702, 0.22678686],
       [0.73886324, 0.4948045 ]])

In [69]:
a[1][1]      #to acces elements of array through index

0.9477063900107072

In [70]:
ar=np.random.randint(1,100,(5,3))

In [71]:
ar>56     #print true for values greater than 56n from ar

array([[ True,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False, False]])

In [72]:
ar[ar>56]

array([64, 70, 66, 90, 70])

In [73]:
ar[2:4,[1,2]]

array([[44, 53],
       [28, 38]])

In [74]:
#Numpy -Broadcasting

In [75]:
arr = np.zeros((4,4))

In [76]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
row = np.array([1,2,3,4])

In [78]:
row

array([1, 2, 3, 4])

In [79]:
arr+row      # used to add 1,2,3,4 to array rowise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [85]:
col = np.array([[1,2,3,4]])      #adding element columnwise

In [86]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [88]:
arr1 = np.random.randint(1,4,(3,4))

In [89]:
arr1

array([[1, 2, 1, 1],
       [2, 2, 3, 1],
       [1, 3, 2, 3]])

In [90]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.73205081, 1.        ],
       [1.        , 1.73205081, 1.41421356, 1.73205081]])

In [91]:
np.exp(arr1)

array([[ 2.71828183,  7.3890561 ,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 , 20.08553692,  2.71828183],
       [ 2.71828183, 20.08553692,  7.3890561 , 20.08553692]])

In [92]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.47712125, 0.        ],
       [0.        , 0.47712125, 0.30103   , 0.47712125]])