<a href="https://colab.research.google.com/github/000626574705/python/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#sort ,Search &Counting functions.

In [2]:
import numpy as np


In [4]:
arr=np.array([4,3,5,6,9])

In [5]:
arr

array([4, 3, 5, 6, 9])

In [9]:
np.sort(arr)    #sort array elements in ascending order

array([3, 4, 5, 6, 9])

In [8]:
np.searchsorted(arr,45)     #returns the array index where 45 is placed after sorting

5

In [10]:
arr1 = np.array([0,54,456,0,10,15])

In [11]:
np.count_nonzero(arr1)     #return count of nonzero elements present

4

In [12]:
arr

array([4, 3, 5, 6, 9])

In [13]:
np.where(arr>6)      #returns index where arr elements are greater than 6

(array([4]),)

In [14]:
np.extract(arr>2,arr)     #returns vaalue at arr greater than 2

array([4, 3, 5, 6, 9])

In [15]:
#Numpy -Byte Swapping.

In [16]:
arr

array([4, 3, 5, 6, 9])

In [17]:
arr.byteswap()

array([288230376151711744, 216172782113783808, 360287970189639680,
       432345564227567616, 648518346341351424])

In [18]:
#Numpy -Copies &Views

In [19]:
arr




array([4, 3, 5, 6, 9])

In [21]:
a=np.copy(arr)     #d copy ek undr change krenge toh dusre me change hi hone dega

In [27]:
b= arr.view()    #means solo copy shares same location

In [23]:
b=a

In [24]:
b[0]=67

In [25]:
b

array([67,  3,  5,  6,  9])

In [26]:
a

array([67,  3,  5,  6,  9])

In [28]:
#Numpy -Matrix library

In [29]:
import numpy.matlib as nm

In [30]:
nm.zeros(5)      #generate array 1d of entries 0

matrix([[0., 0., 0., 0., 0.]])

In [31]:
nm.ones((3,4))                #array with element one of 3*4

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
nm.eye(5)     #generate  diagonal matrix wuth element 1 as diadonal

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [33]:
#Numpy -Linear Algebra()

In [34]:
arr1 = np.random.randint([[2,3],[4,5]])

In [36]:
arr2 = np.random.randint([[7,3],[8,5]])

In [38]:
np.dot(arr1,arr2)     #for calculating dot product od matrix

array([[0, 0],
       [0, 2]])

In [39]:
arr1@arr2

array([[0, 0],
       [0, 2]])